AWSTemplateFormatVersion: 2010-09-09
Description:
  This template launches an EC2 instance with a sec grp that enables SSH and http.

  
Resources:
  Webserver:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0b5eea76982371e91
      InstanceType: t2.micro
      KeyName: new
      SecurityGroups:
        - !Ref Webserversecgrp
      Tags:
        - Key: Name
          Value: CFN-Instance1
      UserData:
        Fn::Base64: |
         #!/bin/bash
         yum update -y
         yum install -y httpd php
         FOLDER="https://raw.githubusercontent.com/jonasberg034/my-projects/main/Project-101-kittens-carousel-static-website-ec2/static-web"
         cd /var/www/html
         wget $FOLDER/index.html
         wget $FOLDER/cat0.jpg
         wget $FOLDER/cat1.jpg
         wget $FOLDER/cat2.jpg
         wget $FOLDER/cat3.png
         systemctl start httpd
         systemctl enable httpd 
  Webserversecgrp:
     Type: AWS::EC2::SecurityGroup
     Properties:
      GroupDescription: Enables SSH # Required
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

Outputs:
 WebsiteURL:
   Value: !Sub 
     - http://${PublicAddress}
     - PublicAddress:  !GetAtt Webserver.PublicDnsName 
   Description: Kitten Carousel Application URL 